
DROP TABLE IF EXISTS login;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS objects;
DROP TABLE IF EXISTS competitions;

CREATE TABLE IF NOT EXISTS login (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL
);